workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: linux
    environment:
      node: latest
    scripts:
      - name: Build Android app
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
